/**
 * 
 */
package org.xbase.com.actions;

/**
 * @author VAMSI KRISHNA MYALAPALLI (vamsikrishna.vasu@gmail.com)
 *
 */
public enum MigratorActions {
	COLLECTIONCREATED, COLLECTIONDELETED, COLLECTIONEMBEDDED, DATABASECREATED, VIEWCREATED, 
	DATABASEDELETED, INDEXCREATED, INDEXDELETED, SCHEMACREATED, SCHEMADELETED, VIEWDELETED;
}

